project_id = "kqsxscjtlipregkrmucg"

[functions.generate-category-image]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.add-experience-points]
verify_jwt = false

[functions.scan-trott]
verify_jwt = false

[functions.extract-markers]
verify_jwt = false

[functions.bulk-insert-scooters]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.generate-seo]
verify_jwt = false
